name: benchmark

on:
  push: 
    branches: [ develop, main ]

  pull_request:
    branches: [ develop, main ]

permissions:
  contents: write
  deployments: write

jobs:
  crawler:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        run: |
          Invoke-WebRequest -Uri "https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1" -OutFile "dotnet-install.ps1"

          # Install 32bit SDK
          ./dotnet-install -InstallDir "C:\Program Files (x86)\dotnet" -Architecture x86 -Version 6.0.201

          # Install 64bit SDK
          ./dotnet-install -InstallDir "C:\Program Files\dotnet" -Architecture x64 -Version 6.0.201

        shell: pwsh
        
      - name: Run crawler benchmarks
        run: . "C:\Program Files\dotnet\dotnet.exe" run --project .\src\Crawler\test\Benchmarks\Earl.Crawler.Benchmarks.csproj -c Release -- --filter *
        shell: pwsh

      - name: Download cached benchmark results
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-crawler-benchmarks
          path: ./cache

      - name: Publish benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          alert-comment-cc-users: '@cryptoc1'
          alert-threshold: '125%'
          auto-push: false
          comment-on-alert: true
          comment-always: true
          external-data-json-path: ./cache/benchmark-data.json
          fail-threshold: '200%'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: Crawler Benchmarks
          output-file-path: BenchmarkDotNet.Artifacts/results/Earl.Crawler.Benchmarks.CrawlerBenchmarks-report-full-compressed.json
          tool: benchmarkdotnet

      - name: Publish artifact 'crawler-benchmarks'
        uses: actions/upload-artifact@v3
        with:
            name: crawler-benchmarks
            path: BenchmarkDotNet.Artifacts