name: benchmark

on:
  push:
    branches: [ develop, main ]
  
  pull_request:
    branches: [ develop, main ]

permissions:
  contents: write
  deployments: write

jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        
      - name: Run crawler benchmarks
        run: dotnet run --project .\src\Crawler\test\Benchmarks\Earl.Crawler.Benchmarks.csproj -c Release -- -f *

      - name: Download cached benchmark results
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-crawler-benchmarks
          path: ./cache

      - name: Publish benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          alert-comment-cc-users: '@cryptoc1'
          alert-threshold: '125%'
          auto-push: true
          comment-on-alert: true
          comment-always: true
          external-data-json-path: ./cache/benchmark-data.json
          fail-threshold: '200%'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: Crawler Benchmarks
          output-file-path: BenchmarkDotNet.Artifacts/results/Earl.Crawler.Benchmarks-report-full-compressed.json
          tool: 'benchmarkdotnet'

      - name: Publish artifact 'crawler-benchmarks'
        uses: actions/upload-artifact@v3
        with:
            name: crawler-benchmarks
            path: BenchmarkDotNet.Artifacts