name: test

on:
  workflow_run:
    workflows: [ build ]
    types: [ completed ]

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore --force

      - name: Run tests
        run: |
          dotnet test --results-directory TestResults --logger "trx;LogFileName=earl-test-results.trx" --collect:"XPlat Code coverage"

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Earl Test Results
          path: TestResults/earl-test-results.trx
          reporter: dotnet-trx

      #- name: Public coverage results
      #  if: success() || failure()
      #  uses: codecov/codecov-action@v1

      - name: Publish artifact 'earl-test-results'
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
            name: earl-test-results
            path: TestResults